language: go

env:
  - GO111MODULE=on

go:
  - 1.10.x
  - 1.11.x

go_import_path: github.com/Bilibili/discovery

install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - cd cmd/discovery
  - go build
  - gometalinter --vendor --disable-all --enable=gosimple --enable=golint --enable=vet --enable=ineffassign --enable=unconvert \
    --exclude="by other packages, and that stutters; consider calling this" \
    --skip=proto \
    --skip=vendor \
    --skip=.git \
    --tests ./... 
  - ./codecov.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
